### ISSUE TITLE
How do disable "?."

### ISSUE THREAD

**Issue by xin-jin** [xwl/electric-spacing#8]
It is annoying that spaces are also inserted around the dot "." in many modes (e.g., "ess-mode","py-python-shell-mode"). Is there a way to permanently disable it (preferably not editing the source)?

Thanks.

**Comment by xin-jin** [comment]
OK. I redefine electric-spacing-rules in my init.el, and it seems to solve the problem.

**Comment by davidshepherd7** [comment]
Hey, I have [a fork of electric-spacing](https://github.com/davidshepherd7/electric-operator) which allows you to easily modify the spacing rules for individual modes (it's a fork because I added extra dependencies to make it easier for me to write the code). I was going to test it a bit more before I published it to melpa but I could hurry that up if there's some demand.

Anyway: with electric-operator to disable the dot operator in `ess-mode` you would just need to put in your init files

```
(electric-operator-add-rules-for-mode 'ess-mode (cons "." nil))
```

[William: hope it's ok to mention this here. One of the main reasons I wrote all that extra code was to make it easy to change the expansion behaviour without writing any elisp, so it seemed worth mentioning for this issue.]

**Comment by xin-jin** [comment]
Thanks!

**Comment by xin-jin** [comment]
For some reason,

```
(electric-operator-add-rules-for-mode 'ess-mode (cons "." nil))
```

doesn't work (even with `eval-after-load "electric-operator-mode"`). `.` is still inserted with space in ess-mode. What is a possible issue?

And

```
(electric-operator-add-rules
 (cons "+" nil))
```

does not work either.

**Comment by davidshepherd7** [comment]
For the `ess-mode` problem: I think `ess-mode` has a bug where it isn't derived from `prog-mode` (the base programming mode). I'll add rules for ess-mode directly to `electric-operator.el` now.

The second issue might be a bit trickier, I've realised that you can't dynamically change the rules in `prog-mode-rules` (well, you can but they won't propagate to the major mode rule lists). For now it might be easiest to add  `cons "+" nil)` to the rule list for each major mode that you use.

**Comment by xin-jin** [comment]
Sorry, I am not really familiar with elisp, but this code doesn't work for me:

```
(eval-after-load "electric-operator-mode"
  '(electric-operator-add-rules-for-mode 'python-mode
                                      (cons "+" nil)
                                      (cons "-" nil)
                                      (cons "*" nil)
                                      (cons "/" nil)
                                      ))
```

Space is still inserted around, say, `+`.

**Comment by davidshepherd7** [comment]
I think you are using `eval-after-load` incorrectly. It looks like it takes a file name, so you need to specify "electric-operator-mode.el" or the code will never run.

Also this might help with debugging: you can always check the current rule list by running `(electric-operator-get-rules-list)`. It's not an interactive command so you'll need to run it using `M-x eval-expression`. The full output will appear in the `*Messages*` buffer.

**Comment by xin-jin** [comment]
OK. I changed "electric-operator-mode" to "electric-operator", and now it works. Thanks!

**Comment by davidshepherd7** [comment]
For the ess-mode problem can we move the discussion [here](https://github.com/davidshepherd7/electric-operator/issues/3), so that it's associated with the right repository.
