### ISSUE TITLE
+=, *=, /=

### ISSUE THREAD

**Issue by xin-jin** [xwl/electric-spacing#9]
Could you modify the behavior of inserting "=", so that there won't be space before "=" in "+=", "*=", "/="?

**Comment by davidshepherd7** [comment]
Hi,

these cases work for me, at least in the major modes that I've tried. Could you provide more details? Could it be related to your solution to issue #8?

**Comment by xin-jin** [comment]
OK. I see what went wrong. I also comment out the rules for `+`, `-`, `*` and `/`, because in many cases I don't want spaces around them (for instance, I prefer `a*b + c*d` to `a * b + c * d`. Any way to resolve the conflicts? Or maybe implement a function that can quickly remove the automatic space when I don't want them?

**Comment by davidshepherd7** [comment]
I think the easiest way would be to use my [fork](https://github.com/davidshepherd7/electric-operator), one of the main differences is that it's much easier to customise the behaviour of one operator without affecting others.

It's accepted to melpa but still waiting to be built. Should be up sometime today I guess.

Unrelated: github's markdown is misinterpreting your `*` characters as _emphasis_, put them inside backquotes (``) instead of double quotes to fix it.

**Comment by xin-jin** [comment]
I see. Thanks!
